version: 0.2
env:
  shell: /bin/bash
  variables:
    GITHUB_URL: "https://github.com/etcd-io/etcd/releases/download"
    ETCD_VER: "v3.4.13"
    ETCD_ARCH: "amd64"
    ETCD_URL: "${GITHUB_URL}/${ETCD_VER}/etcd-${ETCD_VER}-linux-${ETCD_ARCH}.tar.gz"

phases:
  install:
    commands:
      - yum -y install rpm-build rpm-devel rpmlint rpmdevtools
      - cd /root
      - rpmdev-setuptree
      - curl -L ${ETCD_URL} -o /root/rpmbuild/SOURCES/etcd-${ETCD_VER}-linux-${ETCD_ARCH}.tar.gz
      - tar -C /root/rpmbuild/BUILD -xzvf /root/rpmbuild/SOURCES/etcd-${ETCD_VER}-linux-${ETCD_ARCH}.tar.gz
      - cp /root/rpmbuild/BUILD/etcd-${ETCD_VER}-linux-${ETCD_ARCH}/etcd /root/rpmbuild/BUILD/
      - cp /root/rpmbuild/BUILD/etcd-${ETCD_VER}-linux-${ETCD_ARCH}/etcdctl /root/rpmbuild/BUILD/
  pre_build:
    commands:
      - copy build-etcd/${DISTRO}/${OS_VERSION}/etcd.spec /root/rpmbuild/SPECS/
      - copy build-etcd/${DISTRO}/${OS_VERSION}/etcd.service /root/rpmbuild/BUILD/
      - copy build-etc/${DISTRO}/${OS_VERSION}/etcd.conf /root/rpmbuild/BUILD/
  build:
    commands:
      - cd /root/rpmbuild/
      - rpmbuild -ba SPECS/etcd.spec

artifacts:
  files:
    - RPMS/x86_64/etcd*.rpm